name: Format Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  winston-bot:
    name: 📰 Winston Bot 中文檢查
    runs-on: ubuntu-latest
    steps:
      - name: Winston Bot 中文檢查
        uses: Edit-Mr/WinstonBot-CI@main
        with:
          exts: md
          github_token: ${{ secrets.GITHUB_TOKEN }}
  prettier:
    name: 📰 Prettier 格式化檢查
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install prettier
      - name: Run Prettier check
        run: npx prettier --check .
